# Generated by Django 3.2 on 2022-06-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr1', models.TextField()),
                ('attr2', models.TextField()),
            ],
        ),
    ]
